import { boolean, timestamp, serial } from "drizzle-orm/pg-core";
import { cuid2 } from "drizzle-cuid2/postgres";

/**
 * A reusable ID column for tables that use a CUID2 primary key.
 * Defaults to a random CUID2 generated by the database.
 */
export const id = {
	id: cuid2("id").primaryKey().defaultRandom()
};

/**
 * A reusable ID column for tables that use an auto-incrementing integer.
 * (Kept here as a useful alternative if needed for specific tables).
 */
export const idSerial = {
	id: serial("id").primaryKey()
};

/**
 * A set of reusable timestamp and status columns for tables.
 */
export const timestamps = {
	createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).$onUpdate(
		() => new Date()
	),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: "date" }),
	isActive: boolean("is_active").default(true).notNull()
};
