export default [
	{
		caseNum: "001",
		name: "Juan Dela Cruz",
		surgicalService: "General Surgery",
		status: "Waiting",
		age: 45,
		sex: "M",
		contact: "09171234567",
		waitingTime: "2 days",
	},
	{
		caseNum: "002",
		name: "Maria Santos",
		surgicalService: "Orthopedics",
		status: "In Process",
		age: 32,
		sex: "F",
		contact: "09181234567",
		waitingTime: "1 day",
	},
	{
		caseNum: "003",
		name: "Pedro Reyes",
		surgicalService: "ENT",
		status: "Done",
		age: 28,
		sex: "M",
		contact: "09191234567",
		waitingTime: "3 days",
	},
	{
		caseNum: "004",
		name: "Ana Lopez",
		surgicalService: "OB-GYN",
		status: "Waiting",
		age: 37,
		sex: "F",
		contact: "09201234567",
		waitingTime: "5 days",
	},
];
